<?php $this->headTitle('Sửa sản phẩm');?>
<h1>Thêm Sản Phẩm</h1>
<?php 
 $form = $this->form;
 $form->setAttribute('action', $this->url('db_mau', array('action' => 'edit','id'=> $this->id,)));
 $form->setAttribute('role','form');
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id_san_pham'));
?>
<?php
	$dvt=array(); 
	foreach ($donViTinhs as $donViTinh) 
	{
		$dvt[$donViTinh->id_don_vi_tinh]=$donViTinh->ten_don_vi_tinh;
	}

	$loaiSp=array(); 
	foreach ($loais as $loai) 
	{
		$loaiSp[$loai->id_loai]=$loai->ten_loai;
	}
?>
<table class="table">
	<tr>
		<td>Tên sản phẩm </br>
			<?php echo $this->formElement($form->get('ten_san_pham')); ?></td>
	</tr>
	<tr>
		<td>Đơn vị tính</br>
			<?php 
				$donViTinh=$form->get('id_don_vi_tinh');
				$donViTinh->setValueOptions($dvt);
				echo $this->formElement($donViTinh);
			?>
		</td>
	</tr>
	<tr>
		<td>Loại</br>
			<?php 
				$loai=$form->get('id_loai');
				$loai->setValueOptions($loaiSp);
				echo $this->formElement($loai);	
			?>
		</td>
	</tr>
	<tr>
		<td>
			<?php 
				echo $this->formSubmit($form->get('submit'));
				echo $this->form()->closeTag();
			?>
		</td>
	</tr>
</table>