<?php
 $this->headTitle('Thêm sản phẩm');

 $form->setAttribute('action', $this->url('db_doctrine/crud', array('action' => 'add')));
 $form->setAttribute('role','form');
 $form->prepare();
 echo $this->form()->openTag($form);
 $sanPham=$form->get('san-pham'); 
 echo $this->formHidden($sanPham->get('idSanPham'));
?>

<table class="table">
	<tr>
		<td>Tên sản phẩm </br>
			<?php echo $this->formElement($sanPham->get('tenSanPham')); ?></td>
	</tr>
	<tr>
		<td>Loại</br>
			<?php 
				$donViTinh=$sanPham->get('idDonViTinh');
				$donViTinh->setValueOptions($this->MakeArrayOptionDonViTinh($donViTinhs));
				echo $this->formElement($donViTinh);
			?>
		</td>
	</tr>
	<tr>
		<td>Đơn vị tính</br>
			<?php 
				$loai=$sanPham->get('idLoai');
				$loai->setValueOptions($this->MakeArrayOptionLoai($loais));
				echo $this->formElement($loai);				
			?>
		</td>
	</tr>
	<tr>
		<td>
			<?php 
				echo $this->formSubmit($form->get('submit'));
				echo $this->form()->closeTag();
			?>
		</td>
	</tr>
</table>