<?php
//die(var_dump($sanPhams[0]->getIdDonViTInh()->getTenDonViTinh()));
$title = 'Sản Phẩm';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('db_doctrine/crud', array('action'=>'add'));?>">Thêm sản phẩm</a>
</p>

<table class="table">
<tr>
    <th>Sản phẩm</th>
    <th>Đơn vị tính</th>
    <th>Loại</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($sanPhams as $sanPham) : ?>
<tr>
    <td><?php echo $sanPham->getTenSanPham(); ?></td>
    <td><?php echo $sanPham->getIdDonViTinh()->getTenDonViTinh();?></td>
    <td><?php echo $sanPham->getIdLoai()->getTenLoai();?></td>
    <td>
        <a href="<?php echo $this->url('db_doctrine/crud',
            array('action'=>'edit', 'id' => $sanPham->getIdSanPham()));?>">Sửa</a>
        <a href="<?php echo $this->url('db_doctrine/crud',
            array('action'=>'delete', 'id' => $sanPham->getIdSanPham()));?>">Xóa</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
